
-- 테이블 순서는 관계를 고려하여 한 번에 실행해도 에러가 발생하지 않게 정렬되었습니다.

-- MEM_TB Table Create SQL
CREATE TABLE MEM_TB
(
    `MEM_SQ_PK`          INT             NOT NULL    AUTO_INCREMENT COMMENT '계정 일련 번호', 
    `MEM_REG_DT`         TIMESTAMP       NOT NULL    COMMENT '계정 가입일', 
    `MEM_LAST_LOGIN_DT`  TIMESTAMP       NOT NULL    COMMENT '계정 마지막 로그인 일자', 
    `MEM_STATE`          VARCHAR(20)     NOT NULL    COMMENT '계정 상태', 
    `MEM_NICKNM`         VARCHAR(30)     NOT NULL    COMMENT '계정 이름', 
    `MEM_ID`             VARCHAR(50)     NOT NULL    COMMENT '계정 ID', 
    `MEM_PASSWORD`       VARCHAR(300)    NOT NULL    COMMENT '계정 PW', 
    PRIMARY KEY (MEM_SQ_PK)
);

ALTER TABLE MEM_TB COMMENT '계정 테이블';


-- AUTHGRP_TB Table Create SQL
CREATE TABLE AUTHGRP_TB
(
    `AUTHGRP_SQ_PK`        INT            NOT NULL    AUTO_INCREMENT COMMENT '권한 그룹 일련 번호', 
    `AUTHGRP_NM_UNQ`       VARCHAR(45)    NOT NULL UNIQUE    COMMENT 'UNIQUE', 
    `AUTHGRP_EXPLANATION`  VARCHAR(50)    NOT NULL    COMMENT '권한 그룹 설명', 
    PRIMARY KEY (AUTHGRP_SQ_PK)
);

ALTER TABLE AUTHGRP_TB COMMENT '최소 조회 권한 그룹 테이블';


-- FILE_GROUP_TB Table Create SQL
CREATE TABLE FILE_GROUP_TB
(
    `FILE_GRP_SQ_PK`     INT             NOT NULL    AUTO_INCREMENT COMMENT '파일 그룹 일련 번호', 
    `MEM_FK`             INT             NOT NULL    COMMENT '계정 일련 번호', 
    `AUTHGRP_FK`         INT             NOT NULL    COMMENT '최소 조회 권한', 
    `FILE_GRP_REG_DT`    TIMESTAMP       NOT NULL    COMMENT '파일 그룹 최초 생성일', 
    `FILE_GRP_SAVE_DIR`  VARCHAR(200)    NOT NULL    COMMENT '저장 경로', 
    PRIMARY KEY (FILE_GRP_SQ_PK)
);

ALTER TABLE FILE_GROUP_TB COMMENT '파일 묶음 테이블';

ALTER TABLE FILE_GROUP_TB ADD CONSTRAINT FK_FILE_GROUP_TB_AUTHGRP_FK_AUTHGRP_TB_AUTHGRP_SQ_PK FOREIGN KEY (AUTHGRP_FK)
 REFERENCES AUTHGRP_TB (AUTHGRP_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE FILE_GROUP_TB ADD CONSTRAINT FK_FILE_GROUP_TB_MEM_FK_MEM_TB_MEM_SQ_PK FOREIGN KEY (MEM_FK)
 REFERENCES MEM_TB (MEM_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;


-- AUTH_TB Table Create SQL
CREATE TABLE AUTH_TB
(
    `AUTH_SQ_PK`        INT            NOT NULL    AUTO_INCREMENT COMMENT '권한 일련 번호', 
    `AUTH_NM_UNQ`       VARCHAR(50)    NOT NULL UNIQUE    COMMENT 'UNIQUE', 
    `AUTH_EXPLANATION`  VARCHAR(50)    NOT NULL    COMMENT '권한 설명', 
    PRIMARY KEY (AUTH_SQ_PK)
);

ALTER TABLE AUTH_TB COMMENT '권한 테이블';


-- RES_TB Table Create SQL
CREATE TABLE RES_TB
(
    `RES_SQ_PK`       INT             NOT NULL    AUTO_INCREMENT COMMENT '리소스 일련 번호', 
    `HTTP_METHOD_PK`  VARCHAR(10)     NOT NULL    COMMENT 'HTTP 메소드', 
    `SORT_ORDER`      INT             NOT NULL    COMMENT '순서', 
    `RES_TYPE`        VARCHAR(10)     NOT NULL    COMMENT 'url : URL, method : Method', 
    `RES_NM_UNQ`      VARCHAR(50)     NOT NULL UNIQUE    COMMENT 'UNIQUE', 
    `RES_PATTERN`     VARCHAR(100)    NOT NULL    COMMENT '리소스 패턴', 
    PRIMARY KEY (RES_SQ_PK, HTTP_METHOD_PK)
);

ALTER TABLE RES_TB COMMENT '리소스 테이블(복합키)';


-- CMT_GROUP_TB Table Create SQL
CREATE TABLE CMT_GROUP_TB
(
    `CMT_GRP_SQ_PK`         INT           NOT NULL    AUTO_INCREMENT COMMENT '댓글 그룹 일련 번호', 
    `CMT_GRP_NEW_WRITE_FL`  VARCHAR(1)    NOT NULL    COMMENT 'Y면 신규 작성 가능', 
    PRIMARY KEY (CMT_GRP_SQ_PK)
);

ALTER TABLE CMT_GROUP_TB COMMENT '댓글 그룹 테이블';


-- FREEBRD_GRP_TB Table Create SQL
CREATE TABLE FREEBRD_GRP_TB
(
    `FREEBRD_GRP_SQ_PK`  INT    NOT NULL    AUTO_INCREMENT COMMENT '게시글 그룹 일련 번호', 
    `MEM_FK`             INT    NOT NULL    COMMENT '계정 일련 번호', 
    `CMT_GRP_FK`         INT    NOT NULL    COMMENT '댓글 그룹 일련 번호', 
    `FILE_GRP_FK`        INT    NOT NULL    COMMENT '파일 그룹 일련 번호', 
    `AUTHGRP_FK`         INT    NOT NULL    COMMENT '최소 조회 권한', 
    `FREEBRD_GRP_FK`     INT    NOT NULL    COMMENT 'default 게시글 그룹 일련 번호와 동일', 
    `FREEBRD_GRP_ORDER`  INT    NOT NULL    COMMENT 'default 0', 
    `FREEBRD_GRP_DEPTH`  INT    NOT NULL    COMMENT 'default 1', 
    PRIMARY KEY (FREEBRD_GRP_SQ_PK)
);

ALTER TABLE FREEBRD_GRP_TB COMMENT '자유 게시판 그룹 테이블';

ALTER TABLE FREEBRD_GRP_TB ADD CONSTRAINT FK_FREEBRD_GRP_TB_MEM_FK_MEM_TB_MEM_SQ_PK FOREIGN KEY (MEM_FK)
 REFERENCES MEM_TB (MEM_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE FREEBRD_GRP_TB ADD CONSTRAINT FK_FREEBRD_GRP_TB_CMT_GRP_FK_CMT_GROUP_TB_CMT_GRP_SQ_PK FOREIGN KEY (CMT_GRP_FK)
 REFERENCES CMT_GROUP_TB (CMT_GRP_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE FREEBRD_GRP_TB ADD CONSTRAINT FK_FREEBRD_GRP_TB_FILE_GRP_FK_FILE_GROUP_TB_FILE_GRP_SQ_PK FOREIGN KEY (FILE_GRP_FK)
 REFERENCES FILE_GROUP_TB (FILE_GRP_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE FREEBRD_GRP_TB ADD CONSTRAINT FK_FREEBRD_GRP_TB_AUTHGRP_FK_AUTHGRP_TB_AUTHGRP_SQ_PK FOREIGN KEY (AUTHGRP_FK)
 REFERENCES AUTHGRP_TB (AUTHGRP_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE FREEBRD_GRP_TB ADD CONSTRAINT FK_FREEBRD_GRP_TB_FREE_GRP_FK_FREEBRD_GRP_TB_FREEBRD_GRP_SQ_PK FOREIGN KEY (FREEBRD_GRP_FK)
 REFERENCES FREEBRD_GRP_TB (FREEBRD_GRP_SQ_PK) ON DELETE RESTRICT ON UPDATE RESTRICT;


-- MEM_AUTH_TB Table Create SQL
CREATE TABLE MEM_AUTH_TB
(
    `MEM_FK_PK`   INT    NOT NULL    COMMENT '계정 일련 번호', 
    `AUTH_FK_PK`  INT    NOT NULL    COMMENT '권한 일련 번호', 
    PRIMARY KEY (MEM_FK_PK, AUTH_FK_PK)
);

ALTER TABLE MEM_AUTH_TB COMMENT '계정-권한 테이블(복합키)';

ALTER TABLE MEM_AUTH_TB ADD CONSTRAINT FK_MEM_AUTH_TB_MEM_FK_PK_MEM_TB_MEM_SQ_PK FOREIGN KEY (MEM_FK_PK)
 REFERENCES MEM_TB (MEM_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MEM_AUTH_TB ADD CONSTRAINT FK_MEM_AUTH_TB_AUTH_FK_PK_AUTH_TB_AUTH_SQ_PK FOREIGN KEY (AUTH_FK_PK)
 REFERENCES AUTH_TB (AUTH_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;


-- RES_AUTH_TB Table Create SQL
CREATE TABLE RES_AUTH_TB
(
    `RES_FK_PK`   INT    NOT NULL    COMMENT '리소스 일련 번호', 
    `AUTH_FK_PK`  INT    NOT NULL    COMMENT '권한 일련 번호', 
    PRIMARY KEY (RES_FK_PK, AUTH_FK_PK)
);

ALTER TABLE RES_AUTH_TB COMMENT '리소스-권한 테이블(복합키)';

ALTER TABLE RES_AUTH_TB ADD CONSTRAINT FK_RES_AUTH_TB_RES_FK_PK_RES_TB_RES_SQ_PK FOREIGN KEY (RES_FK_PK)
 REFERENCES RES_TB (RES_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE RES_AUTH_TB ADD CONSTRAINT FK_RES_AUTH_TB_AUTH_FK_PK_AUTH_TB_AUTH_SQ_PK FOREIGN KEY (AUTH_FK_PK)
 REFERENCES AUTH_TB (AUTH_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;


-- AUTHGRP_AUTH_TB Table Create SQL
CREATE TABLE AUTHGRP_AUTH_TB
(
    `AUTHGRP_FK_PK`  INT    NOT NULL    COMMENT '권한 그룹 일련 번호', 
    `AUTH_FK_PK`     INT    NOT NULL    COMMENT '권한 일련 번호', 
    PRIMARY KEY (AUTHGRP_FK_PK, AUTH_FK_PK)
);

ALTER TABLE AUTHGRP_AUTH_TB COMMENT '권한 그룹-권한 테이블(복합키)';

ALTER TABLE AUTHGRP_AUTH_TB ADD CONSTRAINT FK_AUTHGRP_AUTH_TB_AUTHGRP_FK_PK_AUTHGRP_TB_AUTHGRP_SQ_PK FOREIGN KEY (AUTHGRP_FK_PK)
 REFERENCES AUTHGRP_TB (AUTHGRP_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE AUTHGRP_AUTH_TB ADD CONSTRAINT FK_AUTHGRP_AUTH_TB_AUTH_FK_PK_AUTH_TB_AUTH_SQ_PK FOREIGN KEY (AUTH_FK_PK)
 REFERENCES AUTH_TB (AUTH_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;


-- BLOCK_TB Table Create SQL
CREATE TABLE BLOCK_TB
(
    `BLOCK_SQ_PK`      INT             NOT NULL    AUTO_INCREMENT COMMENT '차단 일련 번호', 
    `MEM_FK`           INT             NOT NULL    COMMENT '계정 일련 번호', 
    `BLOCK_REG_DT`     TIMESTAMP       NOT NULL    COMMENT '차단 등록일', 
    `BLOCK_START_DT`   TIMESTAMP       NOT NULL    COMMENT '차단 시작 일자', 
    `BLOCK_EXPIRE_DT`  TIMESTAMP       NOT NULL    COMMENT '차단 만료 일자', 
    `BLOCK_CAUSE`      VARCHAR(300)    NOT NULL    COMMENT '차단 사유', 
    PRIMARY KEY (BLOCK_SQ_PK)
);

ALTER TABLE BLOCK_TB COMMENT '차단 계정 테이블';

ALTER TABLE BLOCK_TB ADD CONSTRAINT FK_BLOCK_TB_MEM_FK_MEM_TB_MEM_SQ_PK FOREIGN KEY (MEM_FK)
 REFERENCES MEM_TB (MEM_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;


-- FILE_TB Table Create SQL
CREATE TABLE FILE_TB
(
    `FILE_SQ_PK`        INT             NOT NULL    AUTO_INCREMENT COMMENT '파일  일련 번호', 
    `FILE_GRP_FK`       INT             NOT NULL    COMMENT '파일 그룹 일련 번호', 
    `MEM_FK`            INT             NOT NULL    COMMENT '계정 일련 번호', 
    `FILE_REG_DT`       TIMESTAMP       NOT NULL    COMMENT '파일 등록일', 
    `FILE_DOWN_CNT`     INT             NOT NULL    COMMENT '다운로드 수', 
    `FILE_SIZE`         INT(11)         NOT NULL    COMMENT '파일 크기', 
    `FILE_EXTENSION`    VARCHAR(45)     NOT NULL    COMMENT '확장자명', 
    `FILE_ORIGINAL_NM`  VARCHAR(200)    NOT NULL    COMMENT '원본 파일명', 
    `FILE_SAVE_NM`      VARCHAR(200)    NOT NULL    COMMENT '저장 파일명', 
    PRIMARY KEY (FILE_SQ_PK)
);

ALTER TABLE FILE_TB COMMENT '파일 테이블';

ALTER TABLE FILE_TB ADD CONSTRAINT FK_FILE_TB_FILE_GRP_FK_FILE_GROUP_TB_FILE_GRP_SQ_PK FOREIGN KEY (FILE_GRP_FK)
 REFERENCES FILE_GROUP_TB (FILE_GRP_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE FILE_TB ADD CONSTRAINT FK_FILE_TB_MEM_FK_MEM_TB_MEM_SQ_PK FOREIGN KEY (MEM_FK)
 REFERENCES MEM_TB (MEM_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;


-- FREEBRD_TB Table Create SQL
CREATE TABLE FREEBRD_TB
(
    `FREEBRD_SQ_PK`   INT           NOT NULL    AUTO_INCREMENT COMMENT '게시글 일련 번호', 
    `FREEBRD_GRP_FK`  INT           NOT NULL    COMMENT '게시글 그룹 일련 번호', 
    `FREEBRD_REG_DT`  TIMESTAMP     NOT NULL    COMMENT '게시글 등록일', 
    `FREEBRD_TITLE`   TINYTEXT      NOT NULL    COMMENT '게시글 제목', 
    `FREEBRD_BODY`    MEDIUMTEXT    NOT NULL    COMMENT '게시글 본문', 
    PRIMARY KEY (FREEBRD_SQ_PK)
);

ALTER TABLE FREEBRD_TB COMMENT '자유 게시판 상세 테이블';

ALTER TABLE FREEBRD_TB ADD CONSTRAINT FK_FREEBRD_TB_FREEBRD_GRP_FK_FREEBRD_GRP_TB_FREEBRD_GRP_SQ_PK FOREIGN KEY (FREEBRD_GRP_FK)
 REFERENCES FREEBRD_GRP_TB (FREEBRD_GRP_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;


-- CMT_TB Table Create SQL
CREATE TABLE CMT_TB
(
    `CMT_SQ_PK`      INT           NOT NULL    AUTO_INCREMENT COMMENT '댓글 일련 번호', 
    `CMT_GRP_FK`     INT           NOT NULL    COMMENT '댓글 그룹 일련 번호', 
    `MEM_FK`         INT           NOT NULL    COMMENT '계정 일련 번호', 
    `FILE_GRP_FK`    INT           NOT NULL    COMMENT '파일 그룹 일련 번호', 
    `AUTHGRP_FK`     INT           NOT NULL    COMMENT '최소 조회 권한', 
    `CMT_FK`         INT           NOT NULL    COMMENT 'default 댓글 일련 번호와 동일', 
    `CMT_ORDER`      INT           NOT NULL    COMMENT 'default 0', 
    `CMT_DEPTH`      INT           NOT NULL    COMMENT 'default 1', 
    `CMT_REG_DT`     TIMESTAMP     NOT NULL    COMMENT '댓글 최초 작성일', 
    `CMT_MOD_DT`     TIMESTAMP     NOT NULL    COMMENT '댓글 최종 수정일', 
    `CMT_SECRET_FL`  VARCHAR(1)    NOT NULL    COMMENT 'Y면 작성자, 부모댓글 작성자, 게시글 작성자, 관리자만 볼 수 있음', 
    `CMT_BODY`       TINYTEXT      NOT NULL    COMMENT '255글자', 
    PRIMARY KEY (CMT_SQ_PK)
);

ALTER TABLE CMT_TB COMMENT '댓글 테이블';

ALTER TABLE CMT_TB ADD CONSTRAINT FK_CMT_TB_CMT_GRP_FK_CMT_GROUP_TB_CMT_GRP_SQ_PK FOREIGN KEY (CMT_GRP_FK)
 REFERENCES CMT_GROUP_TB (CMT_GRP_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CMT_TB ADD CONSTRAINT FK_CMT_TB_MEM_FK_MEM_TB_MEM_SQ_PK FOREIGN KEY (MEM_FK)
 REFERENCES MEM_TB (MEM_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CMT_TB ADD CONSTRAINT FK_CMT_TB_FILE_GRP_FK_FILE_GROUP_TB_FILE_GRP_SQ_PK FOREIGN KEY (FILE_GRP_FK)
 REFERENCES FILE_GROUP_TB (FILE_GRP_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE CMT_TB ADD CONSTRAINT FK_CMT_TB_AUTHGRP_FK_AUTHGRP_TB_AUTHGRP_SQ_PK FOREIGN KEY (AUTHGRP_FK)
 REFERENCES AUTHGRP_TB (AUTHGRP_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE CMT_TB ADD CONSTRAINT FK_CMT_TB_CMT_FK_AUTHGRP_TB_CMT_SQ_PK FOREIGN KEY (CMT_FK)
 REFERENCES CMT_TB (CMT_SQ_PK) ON DELETE RESTRICT ON UPDATE RESTRICT;


-- TEMP_SAVE_TB Table Create SQL
CREATE TABLE TEMP_SAVE_TB
(
    `TEMP_SAVE_SQ`     INT           NOT NULL    AUTO_INCREMENT COMMENT '임시 저장 일련 번호', 
    `MEM_FK`           INT           NOT NULL    COMMENT '계정 일련 번호', 
    `RES_FK`           INT           NOT NULL    COMMENT '리소스 일련 번호', 
    `FILE_GRP_FK`      INT           NOT NULL    COMMENT '파일 그룹 일련 번호', 
    `TEMP_SAVE_TITLE`  TINYTEXT      NOT NULL    COMMENT '임시 저장 제목', 
    `TEMP_SAVE_BODY`   MEDIUMTEXT    NOT NULL    COMMENT '임시 저장 본문', 
    PRIMARY KEY (TEMP_SAVE_SQ)
);

ALTER TABLE TEMP_SAVE_TB COMMENT '게시글 임시 저장 테이블';

ALTER TABLE TEMP_SAVE_TB ADD CONSTRAINT FK_TEMP_SAVE_TB_MEM_FK_MEM_TB_MEM_SQ_PK FOREIGN KEY (MEM_FK)
 REFERENCES MEM_TB (MEM_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TEMP_SAVE_TB ADD CONSTRAINT FK_TEMP_SAVE_TB_RES_FK_RES_TB_RES_SQ_PK FOREIGN KEY (RES_FK)
 REFERENCES RES_TB (RES_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE TEMP_SAVE_TB ADD CONSTRAINT FK_TEMP_SAVE_TB_FILE_GRP_FK_FILE_GROUP_TB_FILE_GRP_SQ_PK FOREIGN KEY (FILE_GRP_FK)
 REFERENCES FILE_GROUP_TB (FILE_GRP_SQ_PK)  ON DELETE RESTRICT ON UPDATE RESTRICT;

 
 

